<<<<<<< HEAD
# Generated by Django 5.1.1 on 2024-11-27 22:33
=======
# Generated by Django 5.1.1 on 2024-11-29 05:06
>>>>>>> 6481c51628a07f709f72047740b0d016990ac978

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=30, verbose_name='Nombre del producto')),
                ('precio', models.IntegerField(verbose_name='Precio del producto')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripcion del producto')),
                ('tipo_producto', models.CharField(choices=[('A', 'Comida'), ('B', 'Bebida sin Alcohol'), ('C', 'Cervezas'), ('D', 'Bebidas con alcohol'), ('E', 'Botellas')], default='A', max_length=2, verbose_name='El tipo de producto')),
            ],
        ),
    ]
