# Generated by Django 5.1.1 on 2024-12-26 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seccion_productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_seccion', models.CharField(max_length=10, verbose_name='Nombre de la seccion de productos')),
                ('imagen_respaldo_1', models.ImageField(upload_to='imagen_seccion', verbose_name='Imagen de apoyo 1')),
                ('imagen_respaldo_2', models.ImageField(upload_to='imagen_seccion', verbose_name='Imagen de apoyo 2')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='seccion_producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurante.seccion_productos', verbose_name='Seccion a la que pertenece el producto'),
        ),
    ]
