# Generated by Django 5.1.1 on 2024-12-26 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0002_seccion_productos_producto_seccion_producto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seccion_productos',
            options={'verbose_name': 'Seccion'},
        ),
        migrations.RemoveField(
            model_name='producto',
            name='tipo_producto',
        ),
    ]
