# Generated by Django 5.1.1 on 2024-12-26 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0003_alter_seccion_productos_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seccion_productos',
            name='nombre_seccion',
            field=models.CharField(max_length=20, verbose_name='Nombre de la seccion de productos'),
        ),
    ]
