# Generated by Django 5.1.1 on 2025-01-08 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0004_alter_seccion_productos_nombre_seccion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seccion_productos',
            options={'verbose_name': 'Seccione'},
        ),
    ]
