# Generated by Django 5.1.1 on 2025-01-11 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0005_alter_seccion_productos_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='seccion_producto',
        ),
        migrations.CreateModel(
            name='Subseccion_Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_subseccion', models.CharField(max_length=20, verbose_name='Nombre de la subseccion')),
                ('es_visible', models.BooleanField(verbose_name='Dicta si el nombre de la subseccion se muestra en el menu')),
                ('seccion_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurante.seccion_productos', verbose_name='Seccion a la que pertenece el subproducto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='subseccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurante.subseccion_productos', verbose_name='Subseccion a la que pertenece el producto'),
        ),
    ]
