# Generated by Django 5.1.1 on 2025-01-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0006_remove_producto_seccion_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre_producto',
            field=models.CharField(max_length=50, verbose_name='Nombre del producto'),
        ),
    ]
