# Generated by Django 5.1.1 on 2024-11-17 17:39

import django.contrib.auth.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(error_messages={'unique': 'Ya existe un usuario con este nombre de usuario, por favor verifíquelo.'}, max_length=30, unique=True, verbose_name='Nombre de usuario')),
                ('nombre', models.CharField(default='', max_length=30, verbose_name='Nombre de usuario')),
                ('apellido', models.CharField(default='', max_length=30, verbose_name='Apellido de usuario')),
                ('tipo_usuario', models.CharField(choices=[('AD', 'Admin'), ('US', 'User'), ('GU', 'Guest')], default='US', max_length=2, verbose_name='Tipo de usuario')),
                ('email', models.EmailField(error_messages={'unique': 'Ya existe un usuario con este correo electrónico, por favor verifíquelo.'}, max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='customuser_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
