# Generated by Django 5.1.1 on 2024-11-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_apellido_remove_user_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, error_messages={'unique': 'Ya existe un usuario con este correo electrónico, por favor verifíquelo.'}, max_length=254, verbose_name='Correo electrónico'),
        ),
    ]
