# Generated by Django 5.1.1 on 2024-12-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Ya existe un usuario con este correo electrónico, por favor verifíquelo.'}, max_length=254, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.CharField(default='', error_messages={'unique': 'Ya existe un usuario con este número de teléfono, por favor verifíquelo.'}, max_length=15, unique=True, verbose_name='Numero de telefono'),
        ),
    ]
