# Generated by Django 5.1.1 on 2024-12-19 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_email_alter_user_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='juegos_inscritos',
            field=models.JSONField(default=list, verbose_name='Nombres de juegos que ya se inscribio'),
        ),
    ]
