# Generated by Django 5.1.1 on 2024-12-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_juegos_inscritos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.CharField(error_messages={'unique': 'Ya existe un usuario con este número de teléfono, por favor verifíquelo.'}, max_length=15, unique=True, verbose_name='Numero de telefono'),
        ),
    ]
