# Generated by Django 5.1.1 on 2024-12-27 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar del usuario'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.CharField(error_messages={'unique': 'Ya existe un usuario con este número de teléfono, por favor verifíquelo.'}, max_length=15, unique=True, verbose_name='Numero de telefono'),
        ),
    ]
