# Generated by Django 5.1.1 on 2024-12-31 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_avatar_alter_user_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.CharField(max_length=15, verbose_name='Numero de telefono'),
        ),
    ]
