# Generated by Django 5.1.1 on 2024-12-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_torneo', models.CharField(max_length=30, unique=True, verbose_name='Nombre del torneo')),
                ('nombre_juego', models.CharField(max_length=30, verbose_name='Nombre del Juego del que sera el torneo')),
                ('modo_torneo', models.CharField(choices=[('Direct', 'Eliminacion directa'), ('Double', 'Eliminacion doble (loser bracket)'), ('Round', 'Round Robin')], default='Direct', max_length=8)),
                ('imagen', models.ImageField(upload_to='imagen_torneo', verbose_name='Imagen principal del torneo')),
                ('imagen_banner', models.ImageField(null=True, upload_to='imagen_torneo', verbose_name='Banner del torneo')),
                ('fecha', models.DateTimeField(verbose_name='Fecha y Hora del torneo')),
                ('is_defined', models.BooleanField(default=False)),
                ('descripcion', models.TextField(blank=True, max_length=500, null=True, verbose_name='Descripcion breve del torneo')),
                ('reglas', models.TextField(blank=True, max_length=500, null=True, verbose_name='Reglas del torneo (Poner cada regla separada por espacios)')),
            ],
            options={
                'verbose_name': 'torneo',
                'db_table': 'tournaments_torneo',
            },
        ),
    ]
