# Generated by Django 5.1.1 on 2024-11-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='descripcion',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Descripcion breve del torneo'),
        ),
        migrations.AddField(
            model_name='torneo',
            name='reglas',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='Reglas del torneo (Poner cada regla separada por espacios)'),
        ),
    ]
