# Generated by Django 5.1.1 on 2024-11-18 06:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='Torneo',
            name='usuarios_torneo',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Usuarios Inscritos al torneo'),
        ),
    ]
