# Generated by Django 5.1.1 on 2024-10-17 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournament_prueba',
            options={'verbose_name': 'torneo'},
        ),
        migrations.AlterModelOptions(
            name='users_prueba',
            options={'verbose_name': 'prueba usuario'},
        ),
        migrations.AlterModelTable(
            name='tournament_prueba',
            table='tournament_pruebas',
        ),
        migrations.AlterModelTable(
            name='users_prueba',
            table='users_prueba',
        ),
    ]
