# Generated by Django 5.1.1 on 2024-11-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneo',
            name='descripcion',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Descripcion breve del torneo'),
        ),
    ]
