# Generated by Django 5.1.1 on 2024-11-17 19:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_torneo_descripcion_torneo_reglas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='usuariosTorneo',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Usuarios Inscritos al torneo'),
        ),
    ]
