# Generated by Django 5.1.1 on 2024-12-04 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='imagen_banner',
            field=models.ImageField(null=True, upload_to='imagen_torneo', verbose_name='Banner del torneo'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='imagen',
            field=models.ImageField(upload_to='imagen_torneo', verbose_name='Imagen principal del torneo'),
        ),
    ]
