# Generated by Django 5.1.1 on 2024-10-19 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_alter_tournament_prueba_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament_prueba',
            name='tournament_mode',
            field=models.CharField(choices=[('Single', 'Single'), ('2v2', '2V2')], default='Un Jugador', help_text='El tipo de torneo que sera, ya sea de equipos de n jugadores o de un jugador en solitario', max_length=20),
        ),
    ]
