# Generated by Django 5.1.1 on 2024-11-17 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_torneo_usuariostorneo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='torneo',
            old_name='usuariosTorneo',
            new_name='usuarios_torneo',
        ),
    ]
