# Generated by Django 5.1.1 on 2024-12-02 19:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_alter_torneo_usuario_torneo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='jugadores_inscritos',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Usuarios Inscritos al torneo'),
        ),
        migrations.DeleteModel(
            name='Torneo_usuario',
        ),
    ]
