# Generated by Django 5.1.1 on 2024-10-19 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_alter_tournament_prueba_tournament_mode'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tournament_prueba',
            table='Tournament_pruebas',
        ),
        migrations.AlterModelTable(
            name='users_prueba',
            table='Users_prueba',
        ),
    ]
