# Generated by Django 5.1.1 on 2024-12-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_torneo_jugadores_inscritos_delete_torneo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneo',
            name='nombre_torneo',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nombre del torneo'),
        ),
    ]
