# Generated by Django 5.1.1 on 2024-11-28 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_alter_torneo_usuarios_torneo'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='imagen',
            field=models.ImageField(default=None, upload_to='imagen_torneo', verbose_name='Imagen del torneo'),
            preserve_default=False,
        ),
    ]
