# Generated by Django 5.1.1 on 2024-10-27 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_alter_tournament_prueba_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_prueba',
            name='tournament_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tournaments.tournament_prueba', verbose_name='ID del torneo que esta inscrito'),
        ),
    ]
