# Generated by Django 5.1.1 on 2024-10-28 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_alter_users_prueba_tournament_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament_prueba',
            name='matchups_ready',
            field=models.BooleanField(default=False),
        ),
    ]
