# Generated by Django 5.1.1 on 2024-12-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_alter_torneo_nombre_torneo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneo',
            name='descripcion',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Descripcion breve del torneo'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='reglas',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Reglas del torneo (Poner cada regla separada por espacios)'),
        ),
    ]
