# Generated by Django 5.1.1 on 2024-11-29 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_torneo_imagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torneo',
            name='usuarios_torneo',
        ),
        migrations.CreateModel(
            name='Torneo_usuario',
            fields=[
                ('id_torneo_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('id_torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournaments.torneo')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
