# Generated by Django 5.1.1 on 2024-11-03 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_tournament_prueba_matchups_ready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users_prueba',
            name='tournament_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournaments.tournament_prueba', verbose_name='ID del torneo que esta inscrito'),
        ),
    ]
