# Generated by Django 5.1.1 on 2025-01-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_torneo_requisitos_alter_torneo_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneo',
            name='modo_torneo',
            field=models.CharField(choices=[('Direct', 'Eliminacion directa'), ('Round', 'Round Robin')], default='Direct', max_length=8),
        ),
    ]
