# Generated by Django 5.1.1 on 2024-12-02 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_alter_torneo_descripcion_alter_torneo_reglas'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='torneo',
            options={'verbose_name': 'torneo'},
        ),
        migrations.AlterModelTable(
            name='torneo',
            table='Torneo',
        ),
    ]
