# Generated by Django 5.1.1 on 2024-12-02 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_alter_torneo_options_alter_torneo_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='torneo',
            table='tournaments_torneo',
        ),
    ]
