# Generated by Django 5.1.1 on 2024-12-05 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0003_rename_comments_comment'),
        ('reservations', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('disponibilidad_diaria', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='consola_seleccionada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservations.consola'),
        ),
        migrations.CreateModel(
            name='Consola_disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('disponibles', models.PositiveBigIntegerField()),
                ('consola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.consola')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lobby.sucursal')),
            ],
            options={
                'unique_together': {('consola', 'sucursal', 'fecha')},
            },
        ),
    ]
