# Generated by Django 5.1.1 on 2024-11-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('num_personas', models.PositiveIntegerField()),
                ('comentarios', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Reservacion',
        ),
    ]
