# Generated by Django 5.1.1 on 2024-12-09 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_consola_reservation_consola_seleccionada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='telefono',
        ),
    ]
