# Generated by Django 5.1.1 on 2025-01-08 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_remove_reservation_telefono'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consola_disponibilidad',
            options={'verbose_name': 'Disponibilidad consola'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'Reservacione'},
        ),
    ]
