# Generated by Django 5.1.1 on 2024-11-29 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0001_initial'),
        ('restaurante', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SucursalProducto',
            new_name='Sucursal_Producto',
        ),
        migrations.RenameModel(
            old_name='SucursalPromocion',
            new_name='Sucursal_Promocion',
        ),
    ]
