# Generated by Django 5.1.1 on 2024-12-22 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0003_rename_comments_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='imagen',
            field=models.ImageField(default='', upload_to='imagen_promocion', verbose_name='Imagen de la promocion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promocion',
            name='nombre',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promocion',
            name='tiene_vigencia',
            field=models.BooleanField(default=False, verbose_name='Tiene vigencia?'),
        ),
        migrations.AddField(
            model_name='promocion',
            name='vigencia',
            field=models.DateField(blank=True, null=True, verbose_name='Vecha de vencimiento'),
        ),
    ]
