# Generated by Django 5.1.1 on 2024-12-26 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0004_promocion_imagen_promocion_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
