# Generated by Django 5.1.1 on 2025-01-08 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0005_alter_promocion_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comentario'},
        ),
        migrations.AlterModelOptions(
            name='promocion',
            options={'verbose_name': 'Promocione'},
        ),
        migrations.AlterModelOptions(
            name='sucursal',
            options={'verbose_name': 'Sucursale'},
        ),
    ]
